### ISSUE TITLE
plugin err?

### ISSUE THREAD

**Issue by AnoyingShulkerMC** [fuzzbuck/mindustry.io-plugin#40]
got error when installing plugin:
arc.util.ArcRuntimeException: Error reading file: core\assets\sprites\sprites.atlas (absolute)
        at arc.files.Fi.read(Fi.java:208)
        at arc.graphics.g2d.TextureAtlas$TextureAtlasData.<init>(TextureAtlas.java:361)
        at mindustry.plugin.utils.ContentHandler.<init>(ContentHandler.java:56)
        at mindustry.plugin.ioMain.lambda$new$1(ioMain.java:59)
        at arc.Events.lambda$fire$2(Events.java:26)
        at arc.struct.Array.each(Array.java:181)
        at arc.Events.fire(Events.java:26)
        at arc.Events.fire(Events.java:21)
        at mindustry.server.ServerLauncher.init(ServerLauncher.java:83)
        at arc.backend.headless.HeadlessApplication.mainLoop(HeadlessApplication.java:75)
        at arc.backend.headless.HeadlessApplication$1.run(HeadlessApplication.java:63)
Caused by: java.io.FileNotFoundException: core\assets\sprites\sprites.atlas (The system cannot find the path specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at arc.files.Fi.read(Fi.java:204)
        ... 10 more

**Comment by fuzzbuck** [comment]
The new version requires you to have a folder with mindustry assets (used for map preview generation)
![img](https://user-images.githubusercontent.com/54221024/99627756-3245ca80-2a35-11eb-9f12-e1a454231a6d.png)
